### ISSUE TITLE
Clarify instructions please

### ISSUE THREAD

**Issue by Popcaughan** [ManuCart/Cryptocurrency-Portfolio#1]
Hi,

I'm really keen to use this, but can't follow the instructions. Are some of the .js files missing?

The instruction in step 3 "click on the link and search for sheet and enable Google Sheets API" doesn't make sense to me and then in step 4 I'm not clear how to link the new sheet to the scripts that have been created.

Is there an example sheet you can share that I can then make my own copy of?

Thanks!

**Comment by ManuCart** [comment]
Hi,
Yes, the .js files are missing. I work on it.
I post nearly kraken and bittrex .js files

**Comment by ManuCart** [comment]
Updated
