### ISSUE TITLE
 UsingDollars instead of Euro

### ISSUE THREAD

**Issue by mdagkus** [ManuCart/Cryptocurrency-Portfolio#10]
Could you add it if possible?

**Comment by milescristi** [comment]
I'm looking forward to this too 
Thanks, great job!

**Comment by ManuCart** [comment]
Hi,
I'm working on new version with both fiat currency USD and EUR
![img](https://user-images.githubusercontent.com/1827696/36177210-43f0b8c6-1115-11e8-9270-53c39b21a390.png)

**Comment by Tosko4** [comment]
Any idea when this is going to work? I do see a dropdown, but it remains in EURO
![screenshot 2018-03-19 at 15 48 07](https://user-images.githubusercontent.com/1294707/37602631-08760aa2-2b8d-11e8-87aa-f128f3f0fbee.png)

**Comment by ManuCart** [comment]
Please update template sheet and main.js

**Comment by ManuCart** [comment]
![temp](https://user-images.githubusercontent.com/1827696/37607471-6cf9966e-2b98-11e8-919f-9345d2146645.png)

**Comment by ManuCart** [comment]
Now you can choose € or $

**Comment by Tosko4** [comment]
@ManuCart I downloaded the latest template (of a few minutes ago) and the dropdown is only available at deposit. When I change that to $, all the other currencies remain on Euro lol XD
![screenshot 2018-03-19 at 17 24 08](https://user-images.githubusercontent.com/1294707/37608249-5b4bb62a-2b9a-11e8-991d-9103649c8572.png)

**Comment by ManuCart** [comment]
After choosen $ or € you need to update with -> Cryotos Tools -> Update Portfolio
