### ISSUE TITLE
sheet.addMenu

### ISSUE THREAD

**Issue by cryptoTrader9000** [ManuCart/Cryptocurrency-Portfolio#12]
Hello,
When trying to run the function onOpen I get the error: TypeError: Cannot call method "addMenu" of null. (line 6, file "Code").  I have a spreadsheet opened with two tabs, one being Market and the other Config.  Config has my API keys in B14 and 15.  
Thanks.

**Comment by cryptoTrader9000** [comment]
Also, in the binance function I get TypeError: Cannot call method "getSheetByName" of null. (line 4, file "binance").

**Comment by ManuCart** [comment]
Hi,
I think you're on the wrong way.
When you do Click Tools > Script editor... Create script file with File > New > Script file Copy and paste the contents of main.js and save.
You need to do this in google sheet, not in google drive.
The script editor from google drive not working the same as google sheet script editor.
Please control that point it's should be work

**Comment by cryptoTrader9000** [comment]
It works now.  Thank you!
