### ISSUE TITLE
Balance currency not shown if you have a stop order

### ISSUE THREAD

**Issue by calincross** [ManuCart/Cryptocurrency-Portfolio#13]
For example you have stop loss order the  amount will be moved from the balances ...do not where and from where this data could be taken...

**Comment by ManuCart** [comment]
Hi, yes it's a possible bug, please tell for what's exchange it's happens

**Comment by calincross** [comment]
hey its on  Binance

**Comment by ManuCart** [comment]
Done, new version API_Binance.js V1.1
Please update and try

**Comment by calincross** [comment]
working ...
thanks for the quick fix
