### ISSUE TITLE
Sheet Layout

### ISSUE THREAD

**Issue by jhanzo** [ManuCart/Cryptocurrency-Portfolio#19]
You seem to have [a very nice screeshot](https://github.com/ManuCart/Cryptocurrency-Portfolio/blob/master/sample.png) of your Portfolio with color rules and adapted font.

Is there any chance to have a template file ? Like a Google Sheet Template for example. I think coding this in Script Editor is not easy.

**Comment by ManuCart** [comment]
Hi,
Yes, good idea, I need to put this on my todo list.
Not sure how to make a template, but try to do something.

**Comment by ManuCart** [comment]
Updated, please see Readme
