### ISSUE TITLE
Error Msg: 'The coordinates or dimensions of the range are invalid'

### ISSUE THREAD

**Issue by trendline789** [ManuCart/Cryptocurrency-Portfolio#20]
This message appears after clicking Cryptos Tools > Update Portfolio

**Comment by ManuCart** [comment]
Could you please give me some more information.
An other way is to use the ready template
https://docs.google.com/spreadsheets/d/1UvUOEjSXonikKCIstZ065FXniVo8UH6_LqJNOnqLwEg
Try again it should work

**Comment by trendline789** [comment]
Tried again.  Thought I went step by step but there's a very high probability it's "op error" on my end.  Not proficient w/scripts at all.

I'm sure it works well after correct configuration.  

Closing the ticket to save you the trouble.

Appreciate the follow up.
