### ISSUE TITLE
Did the instruction but nothing happens

### ISSUE THREAD

**Issue by s951736** [ManuCart/Cryptocurrency-Portfolio#22]
I'm looking for a simple way to look into my Binance portfolio, this project looks good, but I can't get it to work, nothing happens after I create all scripts and entered API, not sure if I doing this wrong. 
I did all the step in the instruction, in the script editor, it asks me to name every script, and it auto adds .gs at the end of every files' name, like this:
<img width="156" alt="screen shot 2018-02-11 at 8 11 40 pm" src="https://user-images.githubusercontent.com/12233565/36073226-e7d29720-0f67-11e8-9a6d-b5c99080c812.png">
not sure if this cause this sheet not working, now all the numbers still are zero, please help, thanks.

**Comment by ManuCart** [comment]
Hi,
First you can remove Code.gs if it is empty.
Second go back to your created sheet and follow this steps : 
* Return to the spreadsheet and refresh the page
* A couple of seconds after the page's reload you should see a "Crypto" menu at the top.

**Comment by s951736** [comment]
Hello, thanks for the reply, I just deleted Code.gs, but haven't see Crypto menu.
Here's the screenshot of Script editor and spreadsheet now:
![capture](https://user-images.githubusercontent.com/12233565/36076452-3d0226fa-0f97-11e8-897f-3eac32762a86.PNG)

**Comment by ManuCart** [comment]
I can see it on your first image 
At the end of the menu "File" - "Edit" ......."help" and **"Crypto Tools"**
click "Crypto Tools" and "update portfolio"

**Comment by ManuCart** [comment]
![tools](https://user-images.githubusercontent.com/1827696/36076632-11e4e684-0f5f-11e8-8844-44c1eaf47e02.PNG)

**Comment by s951736** [comment]
It works! Thanks!

**Comment by s951736** [comment]
@ManuCart Can you help me to delete the screenshot? Sorry, I accidentally include my mail in that, thanks.

**Comment by ManuCart** [comment]
Ok I do it but I need to search how to

**Comment by ManuCart** [comment]
done
