### ISSUE TITLE
Symbol exception?

### ISSUE THREAD

**Issue by badgerpawz** [ManuCart/Cryptocurrency-Portfolio#23]
Thanks for sharing guys :)

One of my holdings at Bitfinex, Streamer Data Coin (DATA), shows up in the overview as Datum (DAT) - would I need to edit the main.js script to put in an exception to rectify this? Novice coder here so unsure how to proceed.

Best regards,
D

**Comment by ManuCart** [comment]
Hi and welcome on this project
Please update ```API_Bitfinex.js``` and try 
It should work.

**Comment by badgerpawz** [comment]
Perfect, I see what you did there - thanks Manu! :)
