### ISSUE TITLE
Sheet showing #NUM!

### ISSUE THREAD

**Issue by Tosko4** [ManuCart/Cryptocurrency-Portfolio#26]
Next to the Gains and Total value, it should show a percentage. But now it just shows #NUM!

Any idea?
![screenshot 2018-03-19 at 15 47 12](https://user-images.githubusercontent.com/1294707/37602529-d1eec640-2b8c-11e8-8ddc-ef6308a74ddf.png)

**Comment by ManuCart** [comment]
Please update template sheet and main.js

**Comment by Tosko4** [comment]
@ManuCart it's a newly installed Spreadsheet, I am using the latest code you provided on Github

**Comment by ManuCart** [comment]
The latest code for template and main.js just updated for you 5 mins ago
May be I'm too fast

**Comment by Tosko4** [comment]
@ManuCart nope, same issue.

What i did just now:

Downloaded new template, followed the instructions you provide in your README, and still:

![screenshot 2018-03-19 at 17 18 30](https://user-images.githubusercontent.com/1294707/37607985-a21701aa-2b99-11e8-8960-de7bd658ff3b.png)

**Comment by ManuCart** [comment]
Need to put something on DEPOSIT cell.
DEPOSIT is the total you spend to buy cryptos

**Comment by Tosko4** [comment]
@ManuCart Alright, that I didnt do. But the next thing that popped up is. How does the excel sheet know how much profit I have actually made?

Lets say, 50 euro investment in a market where 1 BTC was 1000 dollar, is different than 50 euro investment when 1 BTC was 20.000 $

**Comment by ManuCart** [comment]
It's a very simple calculation.
The sheet just do a multiply with actual price by quantity for all cryptos
And do a substraction from your DEPOSIT
Just an indication were we are winner or loser

**Comment by Tosko4** [comment]
Alright, well in that case, I raised a feature request xD You may close this issue though!
