### ISSUE TITLE
Bittrex

### ISSUE THREAD

**Issue by f24margo** [ManuCart/Cryptocurrency-Portfolio#29]
Screen real balance Bittrex and  Cryptocurrency-Portfolio.Why?Please help me
<img width="1413" alt="balancebittrex" src="https://user-images.githubusercontent.com/607590/39082005-773200c8-4554-11e8-9804-14247e252736.png">
<img width="670" alt="portfolio1" src="https://user-images.githubusercontent.com/607590/39082008-79e34b4c-4554-11e8-9e08-ef338d70f169.png">

**Comment by ManuCart** [comment]
Hi and welcome
Sorry for delay but I was on Holidays
MUSIC is a rank of 482 and I search only 400 first coin on coinmarketcap
please change the line 8 on main.js and change 400 to 600 for exemple
https://github.com/ManuCart/Cryptocurrency-Portfolio/blob/master/main.js#L8
