### ISSUE TITLE
Binance error -1022

### ISSUE THREAD

**Issue by starecml** [ManuCart/Cryptocurrency-Portfolio#39]
Hi, I am facing an error with binance API...

https://www.binance.com/api/v3/account?timestamp=1532171161829&signature=6265db308e4fd6f9df6a23797186f27d3865972ff5703bc2caec1d8992708717 
returns error 400 with
{"code":-1022,"msg":"Signature for this request is not valid."} 

Any ideas? Thanks for help.

**Comment by ManuCart** [comment]
Hi,
Work for me today,
Please be sure to follow this : 
````
Binance
https://www.binance.com/userCenter/createApi.html
Log in into your Binance account and navigate to the Security Settings page
Click on 'API Settings' and create a new key
Check only the 'Read Info' permission
Check Unrestricted (Less Secure) in IP Access Restriction
Enter your Key in B14 cell and your Secret in B15 cell in "Config" sheet
````

**Comment by starecml** [comment]
Yes, it solved my issue, thanks!
