### ISSUE TITLE
Error: Invalid character in base-64 string

### ISSUE THREAD

**Issue by elRadix** [ManuCart/Cryptocurrency-Portfolio#6]
can you check this is error

thank you.

**Comment by ManuCart** [comment]
Could you please give me more informations.
I have no error like this

**Comment by ManuCart** [comment]
Oh I see, it should be a wrong API key or API Secret.
Please check your API in "Config" sheet

**Comment by mdagkus** [comment]
I apologize from the beginning. This message was written in google translate.

I had the same mistake.
When I checked it with debug mode, I noticed that there was a problem with a line that wrote bittirex.
But I was just trying to deal with Binance. I deleted the non-binance functions inside the code and it no longer caused an error.

**Comment by ManuCart** [comment]
I need to do some change to check if key and secret API exist before doing the request

**Comment by elRadix** [comment]
I don't have kraken, yet it keeps producing an error

```
TypeError: Cannot find function search in object 0. at [unknown function](sha.js:25) at [unknown function](sha.js:16)
at Kraken (API_Kraken.js:16)
at Balance (main.js:47)
```

**Comment by Js-per** [comment]
Having the same issue. Included Binance API keys in B14 and B15. App returns error:

`Error: Invalid character in base-64 string`

If I remove Kraken code, app returns:

`ReferenceError: "Kraken" is not defined.`

Have deleted all functions relating to exchanges not in use. Looking forward to an update ManuCart!

Yew.

**Comment by ManuCart** [comment]
Yep! Working on it

**Comment by ManuCart** [comment]
@Js-per have you add this : 
https://github.com/Caligatio/jsSHA/blob/master/src/sha.js

**Comment by elRadix** [comment]
started from scratch, followed the all the steps 
still getting the same base64 error
`
Error: Invalid character in base-64 string at [unknown function](jsSHA:23) at [unknown function](jsSHA:14) at Kraken(API_Kraken.js:18) at Balance(main.js:39)`

**Comment by ManuCart** [comment]
Ok, I need to do some change.
Actually if you paste only api key & secret for binance, it's normal.
I'll try to fix.

**Comment by ManuCart** [comment]
main.js updated to v0.23 please test it
